stages:
  train:
    cmd: python src/train.py ./data/
    deps:
      - ./data/train.pkl
      - ./src/train.py
    params:
      - train.seed
      - train.n_est
      - train.min_split
  evaluate:
    cmd: python src/evaluate.py ./clf.mlem ./data scores.json prc.json roc.json
    deps:
    - ./data
    - ./clf.mlem
    - src/evaluate.py
    metrics:
    - scores.json:
        cache: false
    plots:
    - prc.json:
        cache: false
        x: recall
        y: precision
    - roc.json:
        cache: false
        x: fpr
        y: tpr
