stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - ./data/train.csv
      - ./data/test.csv
    outs:
      - train.pkl
      - test.pkl
  train:
    cmd: python src/train.py ./data/
    deps:
      - ./data/train.pkl
      - train.py
    params:
      - train.seed
      - train.n_est
      - train.min_split
    outs:
      - model.pt
    metrics:
    - results.json:
        cache: false
